### ISSUE TITLE
Ignoring supplementary channels in DM files

### ISSUE THREAD

**Issue by P-Freville** [nikolaos-siomos/ATLAS#14]
Hi Nikos,

Would it be possible to manage a different channels number between DM files and QA files ? Indeed, ATLAS checks if the DM files and the QA files have exactly the same number of channels. But could ATLAS associate the channels contained in the DM file with the ones in the QA files, without generating an error in the case there is more channels in the DM files ? In that case, could ATLAS just ignore those supplementary channels ?

Best regards,
Patrick

**Comment by nikolaos-siomos** [comment]
Hi Patrick,
actually it already works like that but you have to provide the recorder_channel_id and the laser fields in the configuration files that match the corresponding information in the raw file header. Additional channels that are present on the header but not defined in the config file will be ignored. 
For example, your QA files may have 10 channels, your DM files might have 16 channels but you are only interested in processing 6 of those channels. You just have to define those 6 in your configuration file. ATLAS will only complain if one of those channels is missing. Even then, I think you will just get a warning that the channel was not found and that it was ignored. 
Do you have a sample case where ATLAS crashes?

Best regards,
Nikos

**Comment by P-Freville** [comment]
Hi Nikos, 

Yes, you're right. I think I took a wrong way thinking it was the a difference in the number of channels in the DM files and in the normal files. I join you the error I had, but I've noticed that 11 channels in the DM is correct while 8 channels in the measurement isn't normal (it should be 9 in my case). So the error comes from a corrupted measurement file. 
I've just tested with a not corrupted dataset where I have 9 channels in the measurement files and 11 channels in the DM files, and it works fine. 
So excuse me having raised an issue where everything is alright. 

Best regards, 
Patrick 


De: "Nikolaos Siomos" ***@***.***> 
À: "nikolaos-siomos/ATLAS" ***@***.***> 
Cc: "P-Freville" ***@***.***>, "Author" ***@***.***> 
Envoyé: Mardi 16 Juillet 2024 12:15:53 
Objet: Re: [nikolaos-siomos/ATLAS] Ignoring supplementary channels in DM files (Issue #14) 





Hi Patrick, 
actually it already works like that but you have to provide the recorder_channel_id and the laser fields in the configuration files that match the corresponding information in the raw file header. Additional channels that are present on the header but not defined in the config file will be ignored. 
For example, your QA files may have 10 channels, your DM files might have 16 channels but you are only interested in processing 6 of those channels. You just have to define those 6 in your configuration file. ATLAS will only complain if one of those channels is missing. Even then, I think you will just get a warning that the channel was not found and that it was ignored. 
Do you have a sample case where ATLAS crashes? 

Best regards, 
Nikos

**Comment by nikolaos-siomos** [comment]
Hi Patrick,
no worries, thanks for testing!
I will close the issue since the problem was solved.
Best,
Nikos
