### ISSUE TITLE
Bugs found on Version 0.4.1

### ISSUE THREAD

**Issue by solfcarvelo** [nikolaos-siomos/ATLAS#3]
TypeError: '>=' not supported between instances of 'str' and 'float'

![Captura](https://github.com/nikolaos-siomos/ATLAS/assets/73709051/63f17c78-cac4-43b9-8008-c3c27ba75abc)

**Comment by solfcarvelo** [comment]
![Captura_2](https://github.com/nikolaos-siomos/ATLAS/assets/73709051/be1a944c-3480-4813-9777-679da5a05f0a)

**Comment by solfcarvelo** [comment]
![Captura_3](https://github.com/nikolaos-siomos/ATLAS/assets/73709051/5d096788-d1e3-44b2-90b4-3f85076ec452)

**Comment by solfcarvelo** [comment]
![Captura_4](https://github.com/nikolaos-siomos/ATLAS/assets/73709051/9634260f-0f8e-4b32-ac39-79604479c40a)

**Comment by nikolaos-siomos** [comment]
Hi all,
these seem to be variable type issues similar to Issue 4. They should be fixed in v0.4.2 (now available). Please give it a try and let me know so that we can close the issue. You can have a look at the changelog to see what has changed.
Best
