### ISSUE TITLE
New bug found on Version 0.4.2

### ISSUE THREAD

**Issue by solfcarvelo** [nikolaos-siomos/ATLAS#5]
![imagen](https://github.com/nikolaos-siomos/ATLAS/assets/73709051/a37e66b9-7dcc-4ce1-9cb5-c509a864da4c)

**Comment by nikolaos-siomos** [comment]
I can confirm this bug has to do with the ring telecover test that is not so thoroughly tested yet in ATLAS. The quadrant telecover tests can be normally processed if the tlc_rin folder is not provided. The issue will be solved in the upcoming version 0.4.3

**Comment by nikolaos-siomos** [comment]
This is related to #7 I am closing this Issue as it was fixed in version 0.4.3
