### ISSUE TITLE
Error at initializing the Telecover test

### ISSUE THREAD

**Issue by aHafiz11** [nikolaos-siomos/ATLAS#6]
Hi @nikolaos-siomos ,

I encounter an error while trying v0.4.2 of ATLAS:
![image](https://github.com/nikolaos-siomos/ATLAS/assets/87298036/8a45c1e8-4b8b-43b6-8a45-1a127c02ff61)

I tried running the latest ATLAS version on three different datasets. However, the error above only occurred on one of the datasets.
The foldering structure follows the instructions in the manual

**Comment by nikolaos-siomos** [comment]
This is related to #7 I am closing this Issue as it was fixed in version 0.4.3

**Comment by nikolaos-siomos** [comment]
This issue occurred when the  the extra sector (e.g. last north) was not provided. It affects version 0.4.3 and maybe some of the previous versions. 

The issue has been corrected in version 0.4.4.
