### ISSUE TITLE
Error in ring Telecover test

### ISSUE THREAD

**Issue by solfcarvelo** [nikolaos-siomos/ATLAS#7]
![imagen](https://github.com/nikolaos-siomos/ATLAS/assets/73709051/50855e5d-224d-4c2d-91cc-26df385225d0)

**Comment by solfcarvelo** [comment]
![imagen](https://github.com/nikolaos-siomos/ATLAS/assets/73709051/4ddaeca3-bb70-4b0b-88a7-b31a75b6bbee)

**Comment by nikolaos-siomos** [comment]
I am closing this issue as it was fixed by version 0.4.3
